AddCSLuaFile("shared.lua")
AddCSLuaFile("cl_init.lua")
AddCSLuaFile("sh_misc.lua")
AddCSLuaFile("sh_playerscore.lua")
AddCSLuaFile("sh_modes.lua")
AddCSLuaFile("sh_medals.lua")

AddCSLuaFile("gui/cl_hud.lua")
AddCSLuaFile("gui/cl_3d2d.lua")
AddCSLuaFile("gui/cl_vote.lua")
AddCSLuaFile("gui/cl_voteitem.lua")
AddCSLuaFile("gui/cl_scoreboard.lua")
AddCSLuaFile("gui/cl_config.lua")
AddCSLuaFile("gui/cl_team_selection.lua")
AddCSLuaFile("gui/cl_nametags.lua")

include("shared.lua")
include("sv_deathmatch.lua")
include("sh_misc.lua")
include("sh_playerscore.lua")
include("sh_modes.lua")
include("sv_replaceentities.lua")
include("sv_3d2d.lua")
include("sv_playlists.lua")
include("sv_voting.lua")
include("sv_rounds.lua")
include("sv_commands.lua")
include("sh_medals.lua")